services:
  db:
    image: postgres:18-alpine3.22
    container_name: localdevopsplatform-db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: localdevopsplatform-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always

volumes:
  db_data:
