{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Application Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=\"local-devops-platform-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{job=\"local-devops-platform-service\"}[5m])) / sum(rate(flask_http_request_duration_seconds_count{job=\"local-devops-platform-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status)(rate(flask_http_request_total{job=\"local-devops-platform-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"local-devops-platform-service\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_user_count{job=\"local-devops-platform-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Products",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_product_count{job=\"local-devops-platform-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_order_count{job=\"local-devops-platform-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Order Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_avg_order_price{job=\"local-devops-platform-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Orders Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Orders by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(avg(app_orders_pending{job=\"local-devops-platform-service\"}), \"status\", \"Pending\", \"\", \"\")",
     "legendFormat": "{{Pending}}"
    },
    {
     "expr": "label_replace(avg(app_orders_shipped{job=\"local-devops-platform-service\"}), \"status\", \"Shipped\", \"\", \"\")",
     "legendFormat": "{{Shipped}}"
    },
    {
     "expr": "label_replace(avg(app_orders_cancelled{job=\"local-devops-platform-service\"}), \"status\", \"Cancelled\", \"\", \"\")",
     "legendFormat": "{{Cancelled}}"
    }
   ]
  },
  {
   "title": "Orders Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(avg(app_orders_pending{job=\"local-devops-platform-service\"}), \"status\", \"Pending\", \"\", \"\")",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "label_replace(avg(app_orders_shipped{job=\"local-devops-platform-service\"}), \"status\", \"Shipped\", \"\", \"\")",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "label_replace(avg(app_orders_cancelled{job=\"local-devops-platform-service\"}), \"status\", \"Cancelled\", \"\", \"\")",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}